### ISSUE TITLE
Add blocklist of famous quad9 dns

### ISSUE THREAD

**Issue by trimechee** [m0zgen/openbld.net#4]
Hi, it will be great to add blocklist of famous secure Quad9 dns to more security feeling safe please, or add other blocklists of famous secure dns that block malwares virus like blocklist of cira dns, dns0, nextdns, thank you ::

https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/quad9_blocklist.txtAdd blocklist of famous quad9 dns

**Comment by m0zgen** [comment]
Thanks. It's will be added in the service near future.

**Comment by trimechee** [comment]
Great! 💯 🥇 Thank you so much :)

Let's clarify one thing please, I was using quad9 official dns then quad9 official  a few days ago blocked suddenly  my favorite streaming site which is safe, I suppose qud9 has been under threats and pressure :(

so I no longer use the dns of the official quad9 dns, nor dns0 which also blocks my favorite streaming site, and I started looking for alternative dns, and so I recently found a german dns "Dnsforge", and dnsforge offers several servers including a server with a "harden list" i.e. with community blocklists and so I discovered that this community list includes quad9 dns blocklist !!


the blocklists of dnsforge are listed at the bottom ::

https://dnsforge.de/

I am really surprised that an industrial secret like the quad9 blocklist is available like this, I am intrigued, it is a real mystery, and what worries me is that if Openbld includes this blocklist assigned to quad9, will Openbld block my favorite streaming site?

here is the address of this streaming platform used by a streaming site that I use, we hope please that Openbld will not block this important streaming platform vital life saver for me because it contains old anime with a standard quality ideal for my not very powerful internet connection, otherwise if Openbld is going to block this streaming platform, then we hope that quad9 dns will no longer be included in Openbld please if it turns out that this community blocklist assigned to quad9 blocks this streaming platform, thank you very much!

this streaming platform is embedded in this site: second media player (LECTEUR MOON ) in:

https://v5.voiranime.com/anime/mobile-suit-gundam-iron-blooded-orphans/mobile-suit-gundam-tekketsu-no-orphans-04-vostfr/

i use:

chrome://media-internals/

to find the original url address of the streaming platform embed, here it is:

kFrameUrl

https://jmzkzesy.xyz/bdd/787cgcenfxd1?referer=v5.voiranime.com

so the site that Openbld we hope will not block if Openbld integrates quad9 dns blocklist is:

https://jmzkzesy.xyz/

dnsforge, the german dns where I found the quad9 blocklist, has a forum where we can ask questions, maybe it's a good idea to ask dnsforge administator about the origin and reliability of this amazing blocklist attributed to quad9 dns ..... I'm not a developer and I don't understand the technical aspects of blocklists, dns servers .... so I didn't ask them the question, plus I don't use dnsforge ....

https://community.adminforge.de/

https://dnsforge.de/
